# https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html

parameters:
    env(ELASTICSEARCH_HOST): ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            '$index': api_projections

    Elasticsearch\ClientBuilder:
        factory: Elasticsearch\ClientBuilder::create
        shared: false
        calls:
            - [setHosts, [['%env(ELASTICSEARCH_HOST)%']]]
    Elasticsearch\Client:
        factory: ['@Elasticsearch\ClientBuilder', build]

    app.api.projection_document_transformers:
        class: Symfony\Component\DependencyInjection\ServiceLocator
        tags: [container.service_locator]
        arguments:
            -
                App\Entity\User\User: '@App\Api\Projection\DocumentTransformer\UserDocumentTransformer'
                App\Entity\User\PremiumUser: '@App\Api\Projection\DocumentTransformer\UserDocumentTransformer'

    App\Api\ProjectionTypeRegistry:
        arguments:
            '$mappings':
                App\Api\Projection\UserProjection:
                    properties:
                        id: ~
                        email: ~
                        user_id: ~

    App\Api\ProjectionDocumentTransformer:
        arguments:
            '$transformers': '@app.api.projection_document_transformers'
    App\Api\Projection\DocumentTransformer\:
        resource: '../../src/Api/Projection/DocumentTransformer'

    App\Api\InitializeProjectionTypesCommand:
        arguments:
            '$registries': ['@App\Api\ProjectionTypeRegistry']
    App\Api\SynchronizeProjectionsCommand: ~

    App\Api\ProjectionRepository: ~
    App\Api\ProjectionSynchronization:
        arguments:
            '$providers':
                - ['@MsgPhp\User\Repository\UserRepositoryInterface', findAll]
