services:
    _defaults:
        public: false

    # Client
    Elasticsearch\ClientBuilder:
        factory: Elasticsearch\ClientBuilder::create
        calls:
            - [setHosts, [['%env(ELASTICSEARCH_HOST)%']]]

    Elasticsearch\Client:
        factory: ['@Elasticsearch\ClientBuilder', build]
