# https://www.elastic.co/guide/en/elasticsearch/client/php-api/current/_configuration.html

parameters:
    env(ELASTICSEARCH_HOST): ~

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Elasticsearch\ClientBuilder:
        factory: Elasticsearch\ClientBuilder::create
        shared: false
        calls:
            - [setHosts, [['%env(ELASTICSEARCH_HOST)%']]]
    Elasticsearch\Client:
        factory: ['@Elasticsearch\ClientBuilder', build]

    App\Api\InitializeProjectionTypesCommand:
        arguments:
            '$registries': ['@App\Api\ProjectionTypeRegistry']

    App\Api\ProjectionTypeRegistry:
        arguments:
            '$indexes': [api_projections]
            '$mappings':
                App\Api\Resource\User:
                    properties:
                        id: ~
                        email: ~
