parameters:
    env(GOOGLE_OAUTH_CLIENT_ID): ~
    env(GOOGLE_OAUTH_CLIENT_SECRET): ~
    env(FACEBOOK_OAUTH_CLIENT_ID): ~
    env(FACEBOOK_OAUTH_CLIENT_SECRET): ~

hwi_oauth:
    firewall_names:
        - main
    resource_owners:
        google:
            type: google
            client_id: '%env(GOOGLE_OAUTH_CLIENT_ID)%'
            client_secret: '%env(GOOGLE_OAUTH_CLIENT_SECRET)%'
            scope: email
            options:
                csrf: true
        facebook:
            type: facebook
            client_id: '%env(FACEBOOK_OAUTH_CLIENT_ID)%'
            client_secret: '%env(FACEBOOK_OAUTH_CLIENT_SECRET)%'
            scope: email
            options:
                csrf: true
