name: msgphp
recipe: lemp

config:
  php: 7.2
  webroot: public

proxy:
  pma:
    - pma.msgphp.lndo.site

services:
  appserver:
    config:
      vhosts: config/lando/nginx.conf
  pma:
    type: phpmyadmin
  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:6.3
      command: /elastic-entrypoint.sh elasticsearch

tooling:
  sf:
    service: appserver
    description: Run Symfony commands
    cmd: bin/console

events:
  post-start:
    - composer install --prefer-dist --no-suggest
